### ISSUE TITLE
Table definition via Convention over configuration

### ISSUE THREAD

**Issue by alexsandro-xpt** [ServiceStack/PocoDynamo#11]
Today there way to set my entity definition via configuration instead DataAnnotation?
The Data Annotation is dirtying my entity domain, breaking my POCO classes.

**Comment by mythz** [comment]
You can potentially access the backing Metadata for a Type with:

```csharp
var metadataType = DynamoMetadata.GetType(typeof(Poco));
```

Which returns a [DynamoMetadata](https://github.com/ServiceStack/ServiceStack.Aws/blob/daea0db6897541d4f52a9db6fb88eef1807d92a3/src/ServiceStack.Aws/DynamoDb/DynamoMetadata.cs#L335) instance which you can customize but this should only be done on Startup.
