### ISSUE TITLE
Feature request - Map entity to multiple tables

### ISSUE THREAD

**Issue by ajaishankar** [ServiceStack/PocoDynamo#3]
Mapping an entity to multiple tables would be useful for working with historical data - such as time series and infrequently accessed data.

Also in a multi tenant application it would enable mapping an entity to different tables and provision per client throughput.

The api could still remain clean with register, query and scan taking an additional table name argument.

Something like:

```C#
     db.Register<Poco>("Poco", "PocoArchive")
```

**Comment by mythz** [comment]
This API would be unintuitive, unclear and untyped - it's hard to even describe what this feature is supposed to do - as such it's not something that makes a good API for PocoDynamo.

**Comment by ajaishankar** [comment]
Understood, agree it may not be a widely used feature.

I was thinking of it more of it like OrmLite sharding:

https://github.com/ServiceStack/ServiceStack.OrmLite/blob/master/tests/ServiceStack.OrmLite.Tests/UseCase/ShardingUseCase.cs

Anyway we can always fallback to db.DynamoDb as you said.
