### ISSUE TITLE
Partial updates (UpdateItem)

### ISSUE THREAD

**Issue by ajaishankar** [ServiceStack/PocoDynamo#5]
Does poco dynamo already support updating just some of the properties of an item? If not, it might be a nice feature on top the raw UpdateItem api.

**Comment by mythz** [comment]
Thanks for the suggestion, I've just [added support for partial updates](https://github.com/ServiceStack/ServiceStack.Aws/blob/master/tests/ServiceStack.Aws.DynamoDbTests/PocoDynamoUpdateTests.cs) via a simple new `db.UpdateItemNonDefaults()` API where it only updates values of the POCO that aren't null or default, e.g:

If you update an Existing Item with:

```csharp
db.UpdateItemNonDefaults(new Customer { Id = customer.Id, Age = 42 });
```

It only updates the Age, the rest of the `Customer` POCO remains unchanged.

I've also added support for a richer `db.UpdateItem` API where it allows you to Update Values, Add/Subtract from existing values or delete properties, e.g:

```csharp
db.UpdateItem<Customer>(new DynamoUpdateItem
{
    Hash = customer.Id,
    Put = new Dictionary<string, object>
    {
        { "Nationality", "Australian" },
    },
    Add = new Dictionary<string, object>
    {
        { "Age", -1 }
    },
    Delete = new[] { "Name", "Orders" },
});
```

Where this will Change `Nationality` to **Australian**, decrement `Age` by **1** and delete the `Name` string and `Orders` collection.

These new API's are available from v4.0.55 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

**Comment by ajaishankar** [comment]
That is awesome! Thanks @mythz as always...

**Comment by mythz** [comment]
No worries, I've also added a typed version of the above which can be expressed with:

```csharp
db.UpdateItem<Customer>(customer.Id, 
    put: x => x.Nationality = "Australian",
    add: x => x.Age = -1,
    delete: x => new { x.Name, x.Orders });
```

Unfortunately because [Expression Trees doesn't support assignment](http://stackoverflow.com/a/16847364/85785) I couldn't use them for its implementation so have to instead resort to inspecting the side-effects of the lambda, as a result this API can't be used to set to the types default value, e.g:

```csharp
//throws - can't detect default value
db.UpdateItem<Customer>(customer.Id, put: x => x.Nationality = null);
db.UpdateItem<Customer>(customer.Id, put: x => x.Id = 0);
```

But other than default values, it's a nicer typed version of using the untyped `DynamoUpdateItem`.

FYI this API is now in v4.0.55 on MyGet.

**Comment by ajaishankar** [comment]
Demis, I just pulled v4.0.55 from MyGet but don't see the UpdateItem support...

**Comment by ajaishankar** [comment]
Also to get around [Expression Trees doesn't support assignment](http://stackoverflow.com/a/16847364/85785) just sharing a trick I've used before:

```
public class DynamoUpdateItem<T> where T : new()
{
  public DynamoUpdateItem()
  {
    Put = new T();
  }
  public T Put { get; private set; }
}

static void UpdateItem<T>(Expression<Func<DynamoUpdateItem<T>>> updates) where T : new()
{
}

UpdateItem(() => new DynamoUpdateItem<Customer> {
  Put = {
    Name = "Foo",
    Age = 42
  }
});
```

**Comment by mythz** [comment]
> Demis, I just pulled v4.0.55 from MyGet but don't see the UpdateItem support...

You should [clear your MyGet cache](https://github.com/ServiceStack/ServiceStack/wiki/MyGet#redownloading-myget-packages), I've just downloaded it and the latest API added is there:

![myget-aws](https://cloud.githubusercontent.com/assets/89361/14413999/844bffc8-ff58-11e5-99ee-c8d270f85ed2.png)

That version is more verbose than I'd like, I'll play around a bit more to see if I can something a bit nicer.

**Comment by ajaishankar** [comment]
Thanks, clearing the MyGet package cache worked...

**Comment by mythz** [comment]
@ajaishankar thx for the pointer, I've now changed the Typed API to use Expression-based API in this commit: https://github.com/ServiceStack/ServiceStack.Aws/commit/98771dc4aeb760ab3b36e408a9ca5f5c5a746d63

So the typed API above now looks like:

```csharp
db.UpdateItem(customer.Id, 
    put: () => new Customer {
        Nationality = "Australian"
    },
    add: () => new Customer {
        Age = -1
    },
    delete: x => new { x.Name, x.Orders });
```

This change is available from v4.0.55 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

**Comment by ajaishankar** [comment]
That is cool! 

Just a quick question on the lambda.Compile.  Generally in ServiceStack say I have a expression like `Where(x => x.Name == someVar)` is the value of `someVar` fetched each time through a Compile?

Looking at [OrmLite] (https://github.com/ServiceStack/ServiceStack.OrmLite/blob/dc2d6f138d79e586994720f5619acb7c0e42ddcb/src/ServiceStack.OrmLite/Expressions/SqlExpression.cs) source, it seems to be the case.

Would it make sense to cache the compiled lambda somehow? Just for my understanding, no biggie...

**Comment by mythz** [comment]
It's not cachable transparently but the user can store the generated SQL and DB Params from the `SqlExpression` and cache the SQL and swap the db params. But would require a lot more code at each call-site so I'm only expecting this to be done in perf-sensitive areas.

**Comment by ajaishankar** [comment]
k got it thanks demis!

**Comment by ajaishankar** [comment]
MVC has the source for [CachedExpressionCompiler](https://github.com/mono/aspnetwebstack/blob/master/src/Microsoft.Web.Mvc/CachedExpressionCompiler.cs) - maybe SS could use it?

**Comment by mythz** [comment]
not sure, will have to test to see if it's compatible and doesn't break anything.
