### ISSUE TITLE
how do a conditional write in dynamodb with ServiceStack.Aws

### ISSUE THREAD

**Issue by vvenegasv** [ServiceStack/PocoDynamo#8]
Hi, i post this question in StackOverflow [too](http://stackoverflow.com/questions/37995090/how-do-a-conditional-write-in-dynamodb-with-servicestack-aws) 

In dynamoDb, you can do a conditional write see [here](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/WorkingWithItems.html#WorkingWithItems.ConditionalUpdate) and [here](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.Modifying.html#Expressions.Modifying.ConditionalWrites)

Actually, conditional writes are supported by ServiceStack.Aws? There is plans to add this functionallity? 

Thanks

**Comment by mythz** [comment]
Hi I've updated your answer with an example of using the new `UpdateExpression<T>` builder. Note you can submit [feature requests on UserVoice](https://servicestack.uservoice.com/forums/176786-feature-requests).
