### ISSUE TITLE
How insert enum as int in DynamoDb with ServiceStack.Aws

### ISSUE THREAD

**Issue by vvenegasv** [ServiceStack/PocoDynamo#9]
I put this issue in StackOverflow [too](http://stackoverflow.com/questions/38004118/how-insert-enum-as-int-in-dynamodb-with-servicestack-aws) 

how can i save my enums as int in DynamoDb with ServiceStack.Aws? I tryed setting up a EnumAsInt attribute but is not working. Save enums as int in dynamodb is currently supported? Is a bug?

Thanks

**Comment by mythz** [comment]
Hi, I've answered your StackOverflow question with the new configurable support for Enums following OrmLite and ServiceStack.Text Conventions. 

Note: you don't need to double-post, we actively monitor StackOverflow and were already working on a solution before seeing this issue.
